
import { useParams, useNavigate } from 'react-router-dom';
import { useStore } from '../store/useStore';
import type { ContractStatus } from '../types';
import { Button } from '../components/ui/Button';
import { Badge } from '../components/ui/Badge';
import { Card } from '../components/ui/Card';
import { ArrowLeft, Check, Send, PenTool, Lock, XCircle, Download } from 'lucide-react';
import { cn } from '../utils/cn';
import { format } from 'date-fns';

const LIFECYCLE_STEPS: ContractStatus[] = ['created', 'approved', 'sent', 'signed', 'locked'];

export function ContractView() {
    const { id } = useParams();
    const navigate = useNavigate();
    const { contracts, blueprints, updateContractStatus } = useStore();

    const contract = contracts.find(c => c.id === id);
    const blueprint = blueprints.find(b => b.id === contract?.blueprintId);

    if (!contract || !blueprint) {
        return <div>Contract not found</div>;
    }

    const currentStepIndex = LIFECYCLE_STEPS.indexOf(contract.status);
    const isRevoked = contract.status === 'revoked';

    const handleStatusChange = (newStatus: ContractStatus) => {
        updateContractStatus(contract.id, newStatus);
    };

    const signContract = () => {
        // In a real app, this would open a signature modal
        updateContractStatus(contract.id, 'signed');
    };

    return (
        <div className="flex gap-6 h-[calc(100vh-8rem)]">
            {/* Left: Contract Content */}
            <div className="flex-1 flex flex-col gap-6">
                <div className="flex items-center gap-4">
                    <Button variant="ghost" size="icon" onClick={() => navigate('/')}>
                        <ArrowLeft className="w-5 h-5" />
                    </Button>
                    <div className="flex items-center gap-3">
                        <h1 className="text-2xl font-bold text-slate-800">{contract.name}</h1>
                        <Badge status={contract.status} />
                    </div>
                </div>

                <div className="flex-1 bg-slate-200/50 rounded-xl border border-slate-200/60 overflow-y-auto p-8 flex justify-center">
                    <div className="w-full max-w-3xl bg-white shadow-2xl rounded-sm p-12 space-y-8 min-h-[800px] relative">
                        <div className="border-b-2 border-slate-900 pb-4 mb-8 flex justify-between items-end">
                            <div>
                                <h2 className="text-3xl font-serif font-bold text-slate-900">{contract.name}</h2>
                                <p className="text-slate-500 mt-2">DRAFTED ON {format(new Date(contract.createdAt), 'MMMM d, yyyy').toUpperCase()}</p>
                            </div>
                            <div className="text-right">
                                <p className="text-xs text-slate-400">ID: {contract.id.slice(0, 8)}</p>
                            </div>
                        </div>

                        <div className="space-y-8">
                            {blueprint.fields.map((field) => (
                                <div key={field.id} className="space-y-1">
                                    <span className="text-xs uppercase tracking-wider text-slate-500 font-semibold">{field.label}</span>
                                    <div className={cn(
                                        "p-3 rounded bg-slate-50 border border-slate-100 text-slate-800 font-medium",
                                        field.type === 'signature' && "border-2 border-dashed h-24 flex items-end justify-center pb-2 text-slate-400 italic"
                                    )}>
                                        {field.type === 'checkbox'
                                            ? (contract.fieldValues[field.id] ? 'Checked' : 'Unchecked')
                                            : (contract.fieldValues[field.id] || (field.type === 'signature' ? (contract.status === 'signed' || contract.status === 'locked' ? 'Signed Digitally' : 'Waiting for signature') : '-'))}
                                    </div>
                                </div>
                            ))}
                        </div>

                        <div className="mt-12 pt-8 border-t border-slate-200 flex justify-between text-xs text-slate-400 font-mono">
                            <span>Generated by ContractFlow</span>
                            <span>{contract.status === 'locked' ? 'OFFICIAL RECORD - LOCKED' : 'DRAFT VERSION'}</span>
                        </div>

                        {isRevoked && (
                            <div className="absolute inset-0 bg-white/50 backdrop-blur-sm flex items-center justify-center z-10">
                                <div className="bg-red-50 border-2 border-red-200 p-8 rounded-full shadow-2xl transform -rotate-12">
                                    <span className="text-4xl font-black text-red-500 uppercase border-4 border-red-500 px-6 py-2 rounded-lg">Revoked</span>
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </div>

            {/* Right: Lifecycle & Actions */}
            <div className="w-96 flex flex-col gap-6">
                <Card className="flex-1 bg-white border-slate-200 shadow-xl overflow-hidden flex flex-col">
                    <div className="p-4 border-b border-slate-100 bg-slate-50/50">
                        <h3 className="font-semibold text-slate-900">Lifecycle Management</h3>
                    </div>

                    <div className="p-6 flex-1 overflow-y-auto">
                        {/* Timeline */}
                        <div className="space-y-8 relative before:absolute before:left-4 before:top-2 before:bottom-2 before:w-0.5 before:bg-slate-100">
                            {LIFECYCLE_STEPS.map((step, idx) => {
                                const stepIndex = LIFECYCLE_STEPS.indexOf(step);
                                const isCompleted = currentStepIndex > stepIndex;
                                const isCurrent = currentStepIndex === stepIndex;
                                // const isUpcoming = currentStepIndex < stepIndex; // keep used for logic if needed or remove

                                // Handle revoked state separately in display if needed, but linear flow is nicer.
                                if (isRevoked) {
                                    // Show frozen state
                                }

                                return (
                                    <div key={step} className="relative flex gap-4">
                                        <div className={cn(
                                            "w-8 h-8 rounded-full flex items-center justify-center border-2 z-10 bg-white transition-colors",
                                            isCompleted ? "border-brand-500 text-brand-500" :
                                                isCurrent ? "border-brand-500 bg-brand-500 text-white shadow-lg shadow-brand-500/30" :
                                                    "border-slate-200 text-slate-300"
                                        )}>
                                            {isCompleted ? <Check className="w-4 h-4" /> : idx + 1}
                                        </div>
                                        <div className="pt-1">
                                            <p className={cn("font-semibold text-sm capitalize", isCurrent ? "text-slate-900" : "text-slate-500")}>
                                                {step}
                                            </p>
                                            {isCurrent && !isRevoked && (
                                                <p className="text-xs text-brand-600 mt-1 font-medium">Current Stage</p>
                                            )}
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    </div>

                    <div className="p-6 bg-slate-50 border-t border-slate-100 space-y-3">
                        <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Available Actions</p>

                        {!isRevoked && contract.status !== 'locked' && (
                            <>
                                {contract.status === 'created' && (
                                    <Button className="w-full justify-between" onClick={() => handleStatusChange('approved')}>
                                        Approve Contract <Check className="w-4 h-4" />
                                    </Button>
                                )}
                                {contract.status === 'approved' && (
                                    <Button className="w-full justify-between" onClick={() => handleStatusChange('sent')}>
                                        Send to Client <Send className="w-4 h-4" />
                                    </Button>
                                )}
                                {contract.status === 'sent' && (
                                    <Button className="w-full justify-between" onClick={signContract}>
                                        Sign Contract <PenTool className="w-4 h-4" />
                                    </Button>
                                )}
                                {contract.status === 'signed' && (
                                    <Button className="w-full justify-between" onClick={() => handleStatusChange('locked')}>
                                        Lock & Finalize <Lock className="w-4 h-4" />
                                    </Button>
                                )}

                                <Button
                                    variant="danger"
                                    className="w-full justify-between mt-4 bg-red-50 text-red-600 hover:bg-red-100 hover:text-red-700 border border-red-200 shadow-none"
                                    onClick={() => handleStatusChange('revoked')}
                                >
                                    Revoke Contract <XCircle className="w-4 h-4" />
                                </Button>
                            </>
                        )}

                        {contract.status === 'locked' && (
                            <Button variant="outline" className="w-full justify-between">
                                Download PDF <Download className="w-4 h-4" />
                            </Button>
                        )}

                        {isRevoked && (
                            <div className="p-3 bg-red-50 text-red-700 rounded-lg text-sm text-center">
                                This contract has been revoked and is no longer active.
                            </div>
                        )}
                    </div>
                </Card>
            </div>
        </div>
    );
}
